// Sample data for Rx2Realty

window.R2R_DATA = {
  exam: {
    name: 'Texas Real Estate Salesperson Exam',
    date: new Date('2026-07-18T09:00:00'),
    startedStudying: new Date('2026-04-09'),
    hoursCompleted: 20,
    hoursRequired: 180,
    practiceAvg: 82,
    streak: 23,
  },

  topics: [
    { name: 'Principles of Real Estate I', pct: 30 },
    { name: 'Principles of Real Estate II', pct: 0 },
    { name: 'Law of Agency', pct: 0 },
    { name: 'Law of Contracts', pct: 0 },
    { name: 'Promulgated Contract Forms', pct: 0 },
    { name: 'Real Estate Finance', pct: 0 },
    { name: 'Sales Agent License Practice Exams', pct: 0 },
    { name: 'Texas Sales Agent License Exam Preparation', pct: 0 },
  ],

  recentSessions: [4, 6, 5, 7, 3, 8, 6, 7, 9, 5, 6, 8, 4, 7],

  posts: [
    {
      id: 'p1',
      title: 'Why a compounding pharmacist is studying real estate',
      excerpt: 'Years of formulating personalized therapies taught me that value gets built in the details — the same instinct that shows up in a well-run deal. Here\'s how the two worlds rhyme.',
      category: 'Journal',
      date: 'Apr 14, 2026',
      readTime: '7 min',
      thumb: 'sage',
      feature: true,
      tags: ['journey', 'career pivot'],
    },
    {
      id: 'p3',
      title: 'Five soft skills pharmacists already have',
      excerpt: 'If you can walk a patient through a compounded therapy, you\'re already doing 60% of what a listing agent does. Here\'s the translation.',
      category: 'Bridge',
      date: 'Apr 6, 2026',
      readTime: '5 min',
      thumb: 'plain',
      tags: ['real estate', 'crossover'],
    },
  ],

  categories: [
    { id: 'all', name: 'All discussions', count: 142 },
    { id: 'pharmacy', name: 'Pharmacy practice', count: 38 },
    { id: 'exam', name: 'RE exam prep', count: 41 },
    { id: 'pivot', name: 'Rx → Realty stories', count: 22 },
    { id: 'investing', name: 'Investing 101', count: 19 },
    { id: 'licensing', name: 'Licensing & CE', count: 14 },
    { id: 'lounge', name: 'The lounge', count: 8 },
  ],

  threads: [
    {
      id: 't1',
      title: 'Anyone else studying while running a full-time pharmacy role?',
      author: 'maya.k',
      role: 'Compounding PharmD, TX',
      avatar: 2,
      category: 'exam',
      replies: 24,
      views: 318,
      lastActivity: '2h ago',
      pinned: true,
      excerpt: 'Long lab days plus nighttime flashcards. Looking for tips on retention when your brain is pudding.',
    },
    {
      id: 't2',
      title: 'Broker sponsorship for a new pharmacist-agent — what to ask?',
      author: 'derek.p',
      role: 'Soon-to-be-licensed',
      avatar: 4,
      category: 'pivot',
      replies: 17,
      views: 204,
      lastActivity: '5h ago',
      excerpt: 'I interviewed with three brokerages. Commission splits vary wildly. What non-obvious questions should I ask?',
    },
    {
      id: 't3',
      title: 'Metoprolol vs. atenolol in CKD patients — real-world experience?',
      author: 'jenn.rx',
      role: 'Clinical PharmD',
      avatar: 1,
      category: 'pharmacy',
      replies: 31,
      views: 487,
      lastActivity: '1d ago',
      excerpt: 'Our hospital protocol just shifted and I\'m noticing more hypotension episodes. Anyone else seeing this?',
    },
    {
      id: 't4',
      title: 'Side hustle or second career? A framework for deciding',
      author: 'rx2realty',
      role: 'Host',
      avatar: 3,
      category: 'pivot',
      replies: 48,
      views: 1120,
      lastActivity: '1d ago',
      excerpt: 'Two years into studying and I finally have clarity. Sharing the three questions I asked myself.',
    },
    {
      id: 't5',
      title: 'Texas Principles II — hardest topics on the exam?',
      author: 'sam.w',
      role: 'PharmD, Austin',
      avatar: 6,
      category: 'exam',
      replies: 12,
      views: 156,
      lastActivity: '2d ago',
      excerpt: 'Trying to prioritize study time. Which chapters surprised you on test day?',
    },
    {
      id: 't6',
      title: 'First rental property: what I wish I knew as a healthcare W-2',
      author: 'priya.h',
      role: 'Pharmacist + landlord',
      avatar: 5,
      category: 'investing',
      replies: 29,
      views: 612,
      lastActivity: '3d ago',
      excerpt: 'The tax implications alone are worth a whole thread. Here\'s my debrief from year one.',
    },
  ],

  threadDetail: {
    id: 't4',
    title: 'Side hustle or second career? A framework for deciding',
    category: 'Rx → Realty stories',
    op: {
      author: 'rx2realty',
      role: 'Host · Texas',
      avatar: 3,
      time: '1 day ago',
      content: [
        'For two years I kept asking the wrong question: "Should I leave pharmacy?" The right question, I finally realized, is "What do I want my weeks to look like in five years?"',
        'Here are the three questions that gave me clarity. I\'ll share mine and I\'d love to hear yours.',
        '<strong>1. What energy do I want to bring home at the end of the day?</strong>',
        'Compounding and partnership work both drain me in a specific way — deep focus, zero margin for error on formulations, constant coordination. Real estate is draining in a different way — negotiation, unpredictable hours, emotional clients. Different shape of tiredness. For me, having both shapes keeps either from grinding me down.',
        '<strong>2. Which skills do I want to compound?</strong>',
        'Both careers reward pattern recognition and trust. But real estate compounds referrals in a way pharmacy doesn\'t. A happy patient rarely sends you five more. A happy seller often does.',
        '<strong>3. What\'s the cost of being wrong?</strong>',
        'Keeping my license active means I can always step back. That safety net made this whole thing possible.',
      ],
      likes: 47,
    },
    replies: [
      {
        author: 'maya.k',
        role: 'PharmD, Dallas',
        avatar: 2,
        time: '22 hours ago',
        content: [
          'Question 1 hits hard. I didn\'t realize how much the "zero margin for error" thing was quietly wrecking me until I spent a weekend shadowing an agent.',
          '<blockquote>"Different shape of tiredness."</blockquote>',
          'Stealing this phrase.',
        ],
        likes: 18,
      },
      {
        author: 'derek.p',
        role: 'Houston · pre-license',
        avatar: 4,
        time: '14 hours ago',
        content: [
          'Great framework. I\'d add a fourth: <em>what\'s the learning curve slope you\'re excited about?</em> I can memorize drug interactions forever, but closing documents and escrow timelines are genuinely fun to learn because they\'re new terrain.',
        ],
        likes: 9,
      },
      {
        author: 'jenn.rx',
        role: 'Clinical PharmD',
        avatar: 1,
        time: '6 hours ago',
        content: [
          'Appreciate this post. I\'m not looking to leave clinical work but I am looking for ways to own my time better. Curious if anyone here kept full-time pharmacy and added RE as a weekend thing — how sustainable was year one?',
        ],
        likes: 4,
      },
    ],
  },

  qa: [
    {
      q: 'How do you keep pharmacy work from leaking into your study time?',
      a: 'Short answer: I don\'t study on heavy lab or partnership days. Long answer: I protect my two "good brain" mornings per week, put my phone in another room, and do focused 90-minute blocks with a timer. The rest of the week I watch videos passively. Treat your attention like a controlled substance — measure doses carefully.',
      asker: 'maya.k',
      topic: 'study',
      likes: 34,
      answers: 6,
    },
    {
      q: 'Can I legally mention my PharmD on my real estate marketing materials?',
      a: 'Texas rules let you list credentials that are current and accurate, but the TREC Canons of Professional Ethics mean you have to be careful not to imply expertise you don\'t have. I checked with my sponsoring broker and we decided to lead with "pharmacist-turned-agent" as a personal story in my bio, not as a selling feature on listings.',
      asker: 'derek.p',
      topic: 'licensing',
      likes: 22,
      answers: 4,
    },
    {
      q: 'Which pharmacy skill translated BEST to real estate?',
      a: 'Patient counseling. Every buyer consult is a medication counseling session in disguise — you\'re walking someone through a high-stakes decision, explaining side effects they didn\'t ask about, and trying to spot the thing they\'re not telling you. If you can consult on a compounded hormone therapy, you can handle a first-time buyer\'s jitters.',
      asker: 'jenn.rx',
      topic: 'bridge',
      likes: 51,
      answers: 11,
    },
    {
      q: 'Do I need to drop to part-time pharmacy to make this work?',
      a: 'I didn\'t. I protect mornings for deep work and keep partnership calls and lab time structured so real estate can fit around them. Sponsoring brokers are used to new agents with day jobs — ask about their track record supporting people who can\'t answer the phone 9-to-5.',
      asker: 'priya.h',
      topic: 'career',
      likes: 19,
      answers: 3,
    },
  ],
};
